savedcmd_rust/core.o := OBJTREE=/home/rustxave/Scrivania/OS-Linux/linux rustc --edition=2021 -Zbinary_dep_depinfo=y -Dunsafe_op_in_unsafe_fn -Drust_2018_idioms -Dnon_ascii_idents -Wmissing_docs -Drustdoc::missing_crate_level_docs -Dclippy::correctness -Dclippy::style -Dclippy::suspicious -Dclippy::complexity -Dclippy::perf -Dclippy::let_unit_value -Dclippy::mut_mut -Dclippy::needless_bitwise_bool -Dclippy::needless_continue -Dclippy::no_mangle_with_rust_abi -Wclippy::dbg_macro --target=./scripts/target.json -Cpanic=abort -Cembed-bitcode=n -Clto=n -Cforce-unwind-tables=n -Ccodegen-units=1 -Csymbol-mangling-version=v0 -Crelocation-model=static -Zfunction-sections=n -Dclippy::float_arithmetic -Copt-level=2 -Cdebug-assertions=n -Coverflow-checks=y -Cdebuginfo=2 @./include/generated/rustc_cfg --cfg no_fp_fmt_parse -Aunused-imports --emit=dep-info=rust/.core.o.d --emit=obj=rust/core.o --emit=metadata=rust/libcore.rmeta --crate-type rlib -L./rust --crate-name core /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs ;llvm-objcopy --redefine-sym __addsf3=__rust__addsf3 --redefine-sym __eqsf2=__rust__eqsf2 --redefine-sym __gesf2=__rust__gesf2 --redefine-sym __lesf2=__rust__lesf2 --redefine-sym __ltsf2=__rust__ltsf2 --redefine-sym __mulsf3=__rust__mulsf3 --redefine-sym __nesf2=__rust__nesf2 --redefine-sym __subsf3=__rust__subsf3 --redefine-sym __unordsf2=__rust__unordsf2 --redefine-sym __adddf3=__rust__adddf3 --redefine-sym __ledf2=__rust__ledf2 --redefine-sym __ltdf2=__rust__ltdf2 --redefine-sym __muldf3=__rust__muldf3 --redefine-sym __unorddf2=__rust__unorddf2 --redefine-sym __muloti4=__rust__muloti4 --redefine-sym __multi3=__rust__multi3 --redefine-sym __udivmodti4=__rust__udivmodti4 --redefine-sym __udivti3=__rust__udivti3 --redefine-sym __umodti3=__rust__umodti3 --redefine-sym __aeabi_fadd=__rust__aeabi_fadd --redefine-sym __aeabi_fmul=__rust__aeabi_fmul --redefine-sym __aeabi_fcmpeq=__rust__aeabi_fcmpeq --redefine-sym __aeabi_fcmple=__rust__aeabi_fcmple --redefine-sym __aeabi_fcmplt=__rust__aeabi_fcmplt --redefine-sym __aeabi_fcmpun=__rust__aeabi_fcmpun --redefine-sym __aeabi_dadd=__rust__aeabi_dadd --redefine-sym __aeabi_dmul=__rust__aeabi_dmul --redefine-sym __aeabi_dcmple=__rust__aeabi_dcmple --redefine-sym __aeabi_dcmplt=__rust__aeabi_dcmplt --redefine-sym __aeabi_dcmpun=__rust__aeabi_dcmpun --redefine-sym __aeabi_uldivmod=__rust__aeabi_uldivmod rust/core.o

source_rust/core.o := /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs

deps_rust/core.o := \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/internal_macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/int_macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/i128.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/i16.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/i32.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/i64.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/i8.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/isize.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/u128.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/u16.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/u32.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/u64.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/u8.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/shells/usize.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/f32.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/f64.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/fmt.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/int_macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/error.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/int_log10.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/nonzero.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/saturating.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/wrapping.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/prelude/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/prelude/v1.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/hint.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mir.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/manually_drop.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/maybe_uninit.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/transmutability.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/alignment.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/metadata.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/unique.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/borrow.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/clone.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp/bytewise.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/num.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/default.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/error.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/marker.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/arith.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/bit.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/control_flow.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/drop.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/generator.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/index.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/index_range.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/range.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/try_trait.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/unsize.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/any.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/ascii.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/drain.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/equality.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/array/iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ascii.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ascii/ascii_char.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/asserting.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/async_iter/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/async_iter/async_iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/async_iter/from_iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell/lazy.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell/once.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/convert.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/decode.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/methods.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_str.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/array_chunks.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/by_ref_sized.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/chain.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/cloned.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/copied.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/cycle.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/enumerate.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/filter_map.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/flatten.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/fuse.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/inspect.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/intersperse.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map_while.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/peekable.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/rev.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/scan.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/skip.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/skip_while.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/step_by.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/take.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/take_while.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/zip.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/range.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/empty.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/from_fn.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/from_generator.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/once.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/once_with.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/repeat.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/repeat_n.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/repeat_with.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/successors.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/accum.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/double_ended.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/exact_size.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/marker.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/unchecked_iterator.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/net/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/net/display_buffer.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/net/ip_addr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/net/parser.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/net/socket_addr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/location.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/panic_info.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/pin.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/sync/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/sync/atomic.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/sync/exclusive.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/builders.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/nofloat.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/num.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/hash/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/hash/sip.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/memchr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/ascii.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/cmp.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/raw.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/rotate.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/select.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/specialize.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/converts.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/count.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/error.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/traits.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/validations.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/pattern.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/lossy.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/time.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/unicode/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/unicode/printable.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/unicode/unicode_data.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/into_future.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/join.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/pending.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/poll_fn.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/ready.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/poll.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/wake.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/ready.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/alloc/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/alloc/global.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/alloc/layout.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/bool.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/escape.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/tuple.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/unit.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/primitive.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/macros.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/barrier/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/barrier/cp15.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/hints.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/registers/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm_shared/registers/aarch32.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/simd.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/simd_llvm.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/armclang.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/v6.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/sat.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/dsp.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/simd32.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/arm/ex.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/arch.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/mod.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/swizzle.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/intrinsics.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/alias.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/cast.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements/const_ptr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements/float.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements/int.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements/mut_ptr.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/elements/uint.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/eq.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/fmt.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/iter.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/lane_count.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/masks.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/masks/full_masks.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/masks/to_bitmask.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/ops.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/ops/assign.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/ops/deref.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/ops/unary.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/ord.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/select.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/swizzle_dyn.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/vector.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/vendor.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/vendor/arm.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/panic.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/error.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_char.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_schar.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_uchar.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_short.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_ushort.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_int.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_uint.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_long.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_ulong.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_longlong.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_ulonglong.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_float.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_double.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/c_void.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/core_arch_docs.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/core_simd_docs.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/primitive_docs.rs \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/process_exit.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/string_string.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/fs_file.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/box_into_raw.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/net_tosocketaddrs.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/io_seek.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/io_bufread.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/io_read.md \
  /home/rustxave/.rustup/toolchains/1.71.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../primitive_docs/io_write.md \

rust/core.o: $(deps_rust/core.o)

$(deps_rust/core.o):
